### ISSUE TITLE
 What is the difference between `read` and `watch`

### ISSUE THREAD

**Issue by est7** [okaryo/CleanArchitectureTodoAppTrainingWithFlutter#42]
```
@riverpod
class CreateTodoUseCaseImpl extends _$CreateTodoUseCaseImpl
    implements CreateTodoUseCase {
  @override
  Future<Todo> build(
    String title,
    String? description,
    bool isCompleted,
    DateTime dueDate,
  ) {
    final TodosRepository repository =
        ref.read(todosRepositoryImplProvider.notifier);
    return repository.createTodo(
      title: title,
      description: description,
      isCompleted: isCompleted,
      dueDate: dueDate,
    );
  }
}
```

```
@riverpod
class GetTodoListUseCaseImpl extends _$GetTodoListUseCaseImpl implements GetTodoListUseCase {
  @override
  Future<List<Todo>> build() async {
    final repository = ref.watch(todosRepositoryImplProvider);
    return repository.valueOrNull ?? [];
  }
}

```

One is `ref.read(todosRepositoryImplProvider.notifier);` and the other is `ref.watch(todosRepositoryImplProvider);`. What is the difference between the two, and why does the first use `read` and the second use `watch`

**Comment by est7** [comment]
@okaryo could you give me some guide?本当にありがとうございます

**Comment by okaryo** [comment]
Since this code is from a forked repository, the exact intention of the implementer is unclear to me.

In Riverpod, `read` is used to retrieve the value from a provider once, while `watch` is used to monitor changes in the provider's value and re-evaluate when it changes. Since it's unlikely that the value of a repository will change frequently during application execution, using either `read` or `watch` should yield the same result. However, the official Riverpod documentation suggests using `watch` unless necessary for optimal usage.

>Using ref.read should be avoided as much as possible because it is not reactive.
It exists for cases where using watch or listen would cause issues. If you can, it is almost always better to use watch/listen, especially watch.

https://riverpod.dev/docs/concepts/reading#using-refread-to-obtain-the-state-of-a-provider:~:text=Using%20ref.read%20should,%2C%20especially%20watch.
